trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: sudo apt-get install --no-install-recommends -y libopenjp2-tools rpm libarchive-tools
  displayName: 'Installing Linux Dependencies'
  condition: startsWith(variables['imageName'], 'ubuntu')

- script: yarn install --frozen-lockfile
  displayName: 'yarn install'

- script: yarn dist
  displayName: 'yarn dist'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: '$(imageName)'
    publishLocation: 'Container'
