name: dependency bump

on:
  schedule:
    cron: "0 10 5 ? * * *"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        node-version:
        - 15

    env:
      BRANCH_NAME: dependency-bump

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: sudo apt-get install --no-install-recommends -y libopenjp2-tools rpm libarchive-tools
      name: Install Linux Dependencies
      if: (startsWith(matrix.os, 'ubuntu'))

    - run: |
        git config user.name github actions
        git config user.email actions@github.com
      name: configure git user

    - run: |
        git checkout $GITHUB_REF
        git branch $BRANCH_NAME
        git checkout $BRANCH_NAME
      name: configure git branch

    - run: yarn upgrade --latest

    - run: |
        git add .
        git commit -m "Dependency Bump"
      name: create git commit

    - run: git push --set-upstream origin $BRANCH_NAME --force

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ matrix.os }}-${{ matrix.node-version }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      env:
        cache-name: node-modules



